name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      # 1. GitHub se latest code lena
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Project ko EC2 ke actual folder me deploy karna
      - name: Deploy project
        env:
          ENV_FILE: ${{ secrets.KEYS }}
        run: |
          rsync -av --delete \
            --exclude='.git' \
            --exclude='venv' \
            ./ /home/ubuntu/youtube-chatbot-using-rag/

          printf '%s' "$ENV_FILE" > /home/ubuntu/youtube-chatbot-using-rag/.env

      # 3. Python dependencies update karna
      - name: Install dependencies
        run: |
          cd /home/ubuntu/youtube-chatbot-using-rag
          /home/ubuntu/youtube-chatbot-using-rag/venv/bin/pip install -r requirements.txt

      # 4. FastAPI restart karna
      - name: Restart backend
        run: |
          sudo systemctl restart youtube-rag
          sudo systemctl is-active youtube-rag
