name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy project
        env:
          ENV_FILE: ${{ secrets.KEYS }}
        run: |
          rsync -av --delete \
            --exclude='.git' \
            --exclude='venv' \
            ./ /home/ubuntu/youtube-chatbot-using-rag/

          printf '%s' "$ENV_FILE" > /home/ubuntu/youtube-chatbot-using-rag/.env

      - name: Check deployment
        run: |
          cd /home/ubuntu/youtube-chatbot-using-rag
          ls -la
